import { MigrationInterface, QueryRunner } from "typeorm";

export class RefatoracaoSistemaCorrida1766487606641 implements MigrationInterface {
    name = 'RefatoracaoSistemaCorrida1766487606641'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`solicitacao\` DROP FOREIGN KEY \`FK_solicitacao_corrida\``);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` DROP FOREIGN KEY \`FK_solicitacao_empresa\``);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` DROP FOREIGN KEY \`FK_solicitacao_funcionario\``);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`createDate\` \`createDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`updateDate\` \`updateDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`motorista\` CHANGE \`createDate\` \`createDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`motorista\` CHANGE \`updateDate\` \`updateDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` DROP COLUMN \`tipoRota\``);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` ADD \`tipoRota\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` CHANGE \`dataHoraAgendada\` \`dataHoraAgendada\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` CHANGE \`funcionarioId\` \`funcionarioId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` CHANGE \`empresaId\` \`empresaId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` CHANGE \`corridaId\` \`corridaId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`rota_ida\` CHANGE \`ordemDasParadas\` \`ordemDasParadas\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`rota_ida\` CHANGE \`geoJsonRota\` \`geoJsonRota\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`rota_volta\` CHANGE \`ordemDasParadas\` \`ordemDasParadas\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`rota_volta\` CHANGE \`geoJsonRota\` \`geoJsonRota\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`corrida\` DROP FOREIGN KEY \`FK_e66d3cbb161f37d275a58f2b3a8\``);
        await queryRunner.query(`ALTER TABLE \`corrida\` DROP FOREIGN KEY \`FK_f0e3dbc2d0601cf88c2787588d1\``);
        await queryRunner.query(`ALTER TABLE \`corrida\` DROP FOREIGN KEY \`FK_10ac37bd4ad3373c874e26bbb97\``);
        await queryRunner.query(`ALTER TABLE \`corrida\` DROP FOREIGN KEY \`FK_396fa7f29311ded13c840745c01\``);
        await queryRunner.query(`ALTER TABLE \`corrida\` CHANGE \`inicioDaCorrida\` \`inicioDaCorrida\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`corrida\` CHANGE \`fimDaCorrida\` \`fimDaCorrida\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`corrida\` CHANGE \`motoristaId\` \`motoristaId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`corrida\` CHANGE \`empresaId\` \`empresaId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`corrida\` CHANGE \`rotaIdaId\` \`rotaIdaId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`corrida\` CHANGE \`rotaVoltaId\` \`rotaVoltaId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`funcionario\` DROP FOREIGN KEY \`FK_a2a616862df841a81cb92f07b8c\``);
        await queryRunner.query(`ALTER TABLE \`funcionario\` DROP FOREIGN KEY \`FK_b119fca44ac4a085869edaf95e7\``);
        await queryRunner.query(`ALTER TABLE \`funcionario\` CHANGE \`createDate\` \`createDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`funcionario\` CHANGE \`updateDate\` \`updateDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`funcionario\` CHANGE \`empresaId\` \`empresaId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`funcionario\` CHANGE \`logradouroId\` \`logradouroId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`empresa\` DROP FOREIGN KEY \`FK_f855afda47a8dfc4676edb38527\``);
        await queryRunner.query(`ALTER TABLE \`empresa\` CHANGE \`createDate\` \`createDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`empresa\` CHANGE \`updateDate\` \`updateDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`empresa\` CHANGE \`logradouroId\` \`logradouroId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`logradouro\` DROP FOREIGN KEY \`FK_1ebf3f4855cc3dbd601d46cf7fb\``);
        await queryRunner.query(`ALTER TABLE \`logradouro\` CHANGE \`latitude\` \`latitude\` decimal(10,8) NULL`);
        await queryRunner.query(`ALTER TABLE \`logradouro\` CHANGE \`longitude\` \`longitude\` decimal(11,8) NULL`);
        await queryRunner.query(`ALTER TABLE \`logradouro\` CHANGE \`bairroId\` \`bairroId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`bairro\` DROP FOREIGN KEY \`FK_fb1902a2eb6c78aabd731ba8cbb\``);
        await queryRunner.query(`ALTER TABLE \`bairro\` CHANGE \`cidadeId\` \`cidadeId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cidade\` DROP FOREIGN KEY \`FK_2ec6c38998b498e9f517a6c8399\``);
        await queryRunner.query(`ALTER TABLE \`cidade\` CHANGE \`estadoId\` \`estadoId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`estado\` DROP FOREIGN KEY \`FK_9016d04f7981ac3f2cb6f557d16\``);
        await queryRunner.query(`ALTER TABLE \`estado\` CHANGE \`paisId\` \`paisId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` ADD CONSTRAINT \`FK_5c827ca11671dbee95d00857459\` FOREIGN KEY (\`funcionarioId\`) REFERENCES \`funcionario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` ADD CONSTRAINT \`FK_122fa0ea9d4fec2ad67169906ff\` FOREIGN KEY (\`empresaId\`) REFERENCES \`empresa\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` ADD CONSTRAINT \`FK_341996aac7c11eb90eff93e0971\` FOREIGN KEY (\`corridaId\`) REFERENCES \`corrida\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`corrida\` ADD CONSTRAINT \`FK_e66d3cbb161f37d275a58f2b3a8\` FOREIGN KEY (\`motoristaId\`) REFERENCES \`motorista\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`corrida\` ADD CONSTRAINT \`FK_f0e3dbc2d0601cf88c2787588d1\` FOREIGN KEY (\`empresaId\`) REFERENCES \`empresa\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`corrida\` ADD CONSTRAINT \`FK_10ac37bd4ad3373c874e26bbb97\` FOREIGN KEY (\`rotaIdaId\`) REFERENCES \`rota_ida\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`corrida\` ADD CONSTRAINT \`FK_396fa7f29311ded13c840745c01\` FOREIGN KEY (\`rotaVoltaId\`) REFERENCES \`rota_volta\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`funcionario\` ADD CONSTRAINT \`FK_a2a616862df841a81cb92f07b8c\` FOREIGN KEY (\`empresaId\`) REFERENCES \`empresa\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`funcionario\` ADD CONSTRAINT \`FK_b119fca44ac4a085869edaf95e7\` FOREIGN KEY (\`logradouroId\`) REFERENCES \`logradouro\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`empresa\` ADD CONSTRAINT \`FK_f855afda47a8dfc4676edb38527\` FOREIGN KEY (\`logradouroId\`) REFERENCES \`logradouro\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`logradouro\` ADD CONSTRAINT \`FK_1ebf3f4855cc3dbd601d46cf7fb\` FOREIGN KEY (\`bairroId\`) REFERENCES \`bairro\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bairro\` ADD CONSTRAINT \`FK_fb1902a2eb6c78aabd731ba8cbb\` FOREIGN KEY (\`cidadeId\`) REFERENCES \`cidade\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cidade\` ADD CONSTRAINT \`FK_2ec6c38998b498e9f517a6c8399\` FOREIGN KEY (\`estadoId\`) REFERENCES \`estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`estado\` ADD CONSTRAINT \`FK_9016d04f7981ac3f2cb6f557d16\` FOREIGN KEY (\`paisId\`) REFERENCES \`pais\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`estado\` DROP FOREIGN KEY \`FK_9016d04f7981ac3f2cb6f557d16\``);
        await queryRunner.query(`ALTER TABLE \`cidade\` DROP FOREIGN KEY \`FK_2ec6c38998b498e9f517a6c8399\``);
        await queryRunner.query(`ALTER TABLE \`bairro\` DROP FOREIGN KEY \`FK_fb1902a2eb6c78aabd731ba8cbb\``);
        await queryRunner.query(`ALTER TABLE \`logradouro\` DROP FOREIGN KEY \`FK_1ebf3f4855cc3dbd601d46cf7fb\``);
        await queryRunner.query(`ALTER TABLE \`empresa\` DROP FOREIGN KEY \`FK_f855afda47a8dfc4676edb38527\``);
        await queryRunner.query(`ALTER TABLE \`funcionario\` DROP FOREIGN KEY \`FK_b119fca44ac4a085869edaf95e7\``);
        await queryRunner.query(`ALTER TABLE \`funcionario\` DROP FOREIGN KEY \`FK_a2a616862df841a81cb92f07b8c\``);
        await queryRunner.query(`ALTER TABLE \`corrida\` DROP FOREIGN KEY \`FK_396fa7f29311ded13c840745c01\``);
        await queryRunner.query(`ALTER TABLE \`corrida\` DROP FOREIGN KEY \`FK_10ac37bd4ad3373c874e26bbb97\``);
        await queryRunner.query(`ALTER TABLE \`corrida\` DROP FOREIGN KEY \`FK_f0e3dbc2d0601cf88c2787588d1\``);
        await queryRunner.query(`ALTER TABLE \`corrida\` DROP FOREIGN KEY \`FK_e66d3cbb161f37d275a58f2b3a8\``);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` DROP FOREIGN KEY \`FK_341996aac7c11eb90eff93e0971\``);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` DROP FOREIGN KEY \`FK_122fa0ea9d4fec2ad67169906ff\``);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` DROP FOREIGN KEY \`FK_5c827ca11671dbee95d00857459\``);
        await queryRunner.query(`ALTER TABLE \`estado\` CHANGE \`paisId\` \`paisId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`estado\` ADD CONSTRAINT \`FK_9016d04f7981ac3f2cb6f557d16\` FOREIGN KEY (\`paisId\`) REFERENCES \`pais\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cidade\` CHANGE \`estadoId\` \`estadoId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cidade\` ADD CONSTRAINT \`FK_2ec6c38998b498e9f517a6c8399\` FOREIGN KEY (\`estadoId\`) REFERENCES \`estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bairro\` CHANGE \`cidadeId\` \`cidadeId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bairro\` ADD CONSTRAINT \`FK_fb1902a2eb6c78aabd731ba8cbb\` FOREIGN KEY (\`cidadeId\`) REFERENCES \`cidade\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`logradouro\` CHANGE \`bairroId\` \`bairroId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`logradouro\` CHANGE \`longitude\` \`longitude\` decimal(11,8) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`logradouro\` CHANGE \`latitude\` \`latitude\` decimal(10,8) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`logradouro\` ADD CONSTRAINT \`FK_1ebf3f4855cc3dbd601d46cf7fb\` FOREIGN KEY (\`bairroId\`) REFERENCES \`bairro\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`empresa\` CHANGE \`logradouroId\` \`logradouroId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`empresa\` CHANGE \`updateDate\` \`updateDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`empresa\` CHANGE \`createDate\` \`createDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`empresa\` ADD CONSTRAINT \`FK_f855afda47a8dfc4676edb38527\` FOREIGN KEY (\`logradouroId\`) REFERENCES \`logradouro\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`funcionario\` CHANGE \`logradouroId\` \`logradouroId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`funcionario\` CHANGE \`empresaId\` \`empresaId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`funcionario\` CHANGE \`updateDate\` \`updateDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`funcionario\` CHANGE \`createDate\` \`createDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`funcionario\` ADD CONSTRAINT \`FK_b119fca44ac4a085869edaf95e7\` FOREIGN KEY (\`logradouroId\`) REFERENCES \`logradouro\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`funcionario\` ADD CONSTRAINT \`FK_a2a616862df841a81cb92f07b8c\` FOREIGN KEY (\`empresaId\`) REFERENCES \`empresa\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`corrida\` CHANGE \`rotaVoltaId\` \`rotaVoltaId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`corrida\` CHANGE \`rotaIdaId\` \`rotaIdaId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`corrida\` CHANGE \`empresaId\` \`empresaId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`corrida\` CHANGE \`motoristaId\` \`motoristaId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`corrida\` CHANGE \`fimDaCorrida\` \`fimDaCorrida\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`corrida\` CHANGE \`inicioDaCorrida\` \`inicioDaCorrida\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`corrida\` ADD CONSTRAINT \`FK_396fa7f29311ded13c840745c01\` FOREIGN KEY (\`rotaVoltaId\`) REFERENCES \`rota_volta\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`corrida\` ADD CONSTRAINT \`FK_10ac37bd4ad3373c874e26bbb97\` FOREIGN KEY (\`rotaIdaId\`) REFERENCES \`rota_ida\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`corrida\` ADD CONSTRAINT \`FK_f0e3dbc2d0601cf88c2787588d1\` FOREIGN KEY (\`empresaId\`) REFERENCES \`empresa\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`corrida\` ADD CONSTRAINT \`FK_e66d3cbb161f37d275a58f2b3a8\` FOREIGN KEY (\`motoristaId\`) REFERENCES \`motorista\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rota_volta\` CHANGE \`geoJsonRota\` \`geoJsonRota\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rota_volta\` CHANGE \`ordemDasParadas\` \`ordemDasParadas\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rota_ida\` CHANGE \`geoJsonRota\` \`geoJsonRota\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rota_ida\` CHANGE \`ordemDasParadas\` \`ordemDasParadas\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` CHANGE \`corridaId\` \`corridaId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` CHANGE \`empresaId\` \`empresaId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` CHANGE \`funcionarioId\` \`funcionarioId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` CHANGE \`dataHoraAgendada\` \`dataHoraAgendada\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` DROP COLUMN \`tipoRota\``);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` ADD \`tipoRota\` varchar(10) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`motorista\` CHANGE \`updateDate\` \`updateDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`motorista\` CHANGE \`createDate\` \`createDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`updateDate\` \`updateDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`createDate\` \`createDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` ADD CONSTRAINT \`FK_solicitacao_funcionario\` FOREIGN KEY (\`funcionarioId\`) REFERENCES \`funcionario\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` ADD CONSTRAINT \`FK_solicitacao_empresa\` FOREIGN KEY (\`empresaId\`) REFERENCES \`empresa\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`solicitacao\` ADD CONSTRAINT \`FK_solicitacao_corrida\` FOREIGN KEY (\`corridaId\`) REFERENCES \`corrida\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
    }

}
